n = input('Digite algo:')
print('O tipo primitivo desse valor e ', type(n))
print('so tem espacos?', n.isspace())
print('e um numero?', n.isnumeric())
print('e alfabetico?', n.isalpha())
print('e alfanumerico?', n.isalnum())
print('esta em maisculas?', n.isupper())
print('esta em minuscula?', n.islower())
print('esta capitalizada?', n.istitle())

